<?php

namespace eCommerceBundle\Repository;

/**
 * CestaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CestaRepository extends \Doctrine\ORM\EntityRepository
{
}
