# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        eCommerceBundle\Entity\User: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: eCommerceBundle:User
                property: username
        in_memory:
            memory: ~

    firewalls:
    
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            provider: our_db_provider
            guard:
                authenticators:
                    - eCommerceBundle\Security\UserAuthenticator
            form_login:
                login_path: login
                check_path: login
            logout: true
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/*, roles: ROLE_ADMIN }
